# -*- coding: utf-8 -*-
"""10주차 청소년

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AJgRRcbuoYGdRWjgE2aM7cM-w1UbYwcX
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd

import matplotlib.pyplot as plt

plt.rc('font',family='NanumBarunGothic')

df_eat = pd.read_csv('/content/청소년식생활현황.csv')
df_exe = pd.read_csv('/content/청소년신체운동현황.csv')
df_fat = pd.read_csv('/content/청소년비만.csv')
df_mind = pd.read_csv('/content/청소년정신건강.csv')
df_smoke = pd.read_csv('/content/청소년흡연율현황.csv')
df_drink = pd.read_csv('/content/청소년음주현황.csv')

df_eat

df_eat.columns

x = df_eat['시점']
y1 = df_eat['남학생정크푸드']
y2 = df_eat['여학생정크푸드']

plt.plot(x,y1,marker = 'o')
plt.plot(x,y2,marker = 'o')

plt.xlabel = "something"

#잘못그린 그래프입니다        오류 참고용

df_eat.plot(x='시점' , y=['남학생정크푸드', '여학생정크푸드'],marker = 'o')

df_fat.plot(kind = 'line',x = '시점',y = ['남학생비만율','여학생비만율','전체비만율'],marker = 'o')
plt.ylabel('단위(%)')
plt.title('청소년 비만율 추이')

df_merge = df_eat[['시점','전체아침결식','전체주3회정크푸트']].copy()
df_merge = pd.merge(df_merge,df_fat[['시점','전체비만율','전체이미지왜곡인지']],on='시점',how='left')

df_merge

df_exe

plt.bar(df_merge['시점'],df_merge['전체비만율'],label = '비만율',color = 'r')
plt.plot(df_merge['시점'],df_merge['전체아침결식'],marker = 'o',color = 'b',label='아침결식')
plt.plot(df_exe['시점'],df_exe['전체운동'],marker = 'o',color = 'g',label = '운동')
plt.legend()

plt.xlabel('연도')
plt.ylabel('비율')
plt.tilte('비만울과 아침결식비율관계')
plt.grid()

df_drink

df_merge.columns

df_drink.columns

df_mind

df_mind.columns

df_mind.plot(kind = 'area', x = '시점', y = ['남학생우울증','여학생우울증'])
plt.ylabel('단위(%)')
plt.title('우울감경험율')

df_drink.columns

df_smoke.columns

df_merge.columns

df_merge = pd.concat([df_merge,df_drink[['전체음주율']]],axis = 1)
df_merge = pd.concat([df_merge,df_smoke[['전체흡연율']]],axis =1)
df_merge = pd.concat([df_merge,df_mind[['전체자살','전체스트레스','전체우울증']]],axis =1)
df_merge

!pip install seaborn

import seaborn as sns

df_merge = df_merge.drop('시점',axis=1)

df_merge = df_merge.drop(0,axis=1)

plt.figure(figsize=(15,15))
sns.heatmap(data = df_merge.corr(), annot=True,
fmt = '.1f', linewidths=.5, cmap='Reds')